version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:oracle:thin:@db:1521:xe
      QUARKUS_DATASOURCE_USERNAME: cdit
      QUARKUS_DATASOURCE_PASSWORD: abcd1234
    depends_on:
      - db

  db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db-container
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: abcd1234
      ORACLE_USER: cdit
      ORACLE_DATABASE: xe
