# Configurações comuns para todos os ambientes
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=cdit
quarkus.datasource.password=abcd1234
quarkus.datasource.jdbc.driver=oracle.jdbc.OracleDriver
quarkus.hibernate-orm.database.generation=none
quarkus.datasource.jdbc.min-size=1
quarkus.datasource.jdbc.max-size=10
quarkus.datasource.jdbc.acquire-increment=1
quarkus.datasource.jdbc.idle-timeout=60
quarkus.datasource.jdbc.acquisition-timeout=30

# Habilita o Swagger (SmallRye OpenAPI)
quarkus.smallrye-openapi.enable=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.swagger-ui.always-include=true

# Ambiente dev (fora do Docker)
%dev.quarkus.datasource.jdbc.url=jdbc:oracle:thin:@localhost:1521:xe

# Ambiente prod (dentro do Docker)
# Ambiente prod (dentro do Docker)
%prod.quarkus.datasource.jdbc.url=jdbc:oracle:thin:@database:1521:xe

